---
resources:

 - name: mjackets-api
   type: git
   public: true
   icon: github
   source:
     uri: https://github.com/RoboJackets/mjackets-api.git
     branch: master
     paths: [ci/dockerfiles/mjackets-build/Dockerfile]
     username: x-access-token
     password: ((github-com/token))
   webhook_token: ((webhook-token))

 - name: mjackets-build-image
   type: registry-image
   public: true
   icon: docker
   source:
     repository: robojackets/mjackets-dev
     username: ((hub-docker-com.username))
     password: ((hub-docker-com.password))

jobs:
- name: docker-build
  plan:
  - get: mjackets-api
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: mjackets-api
      outputs:
      - name: image
      params:
        CONTEXT: mjackets-api/ci/dockerfiles/mjackets-build
      run:
        path: build
  - put: mjackets-build-image
    params:
      image: image/image.tar



