#!/bin/bash

# Install script to set up a template project on your computer

echo -e "Please enter name for your mJacket project: "
read name

echo -e "Please enter install directory for your mJacket project: "
read install_path
mkdir -p $install_path

echo "[INFO] Copying template to install directory"
cp -R ./TEMPLATE $install_path

cd $install_path
mv $install_path/TEMPLATE $install_path/$name
cd $name

echo "[INFO] Setting up empty git repository"
git init

echo "[INFO] Downloading mJackets API"
git submodule add https://github.com/RoboJackets/mjackets-api.git
git submodule init
git submodule update
cd ./mjackets-api
git submodule init
git submodule update
cd ..
git add .
git commit -m "initial commit"

echo "[INFO] Installation Complete"
echo "[INFO] A local git repository has been set up in the $install_path/$name directory."
