---
resource_types:
 - name: sonar-runner
   type: docker-image
   source:
     repository: cathive/concourse-sonarqube-resource
     tag: latest # For reproducible builds use a specific tag and don't rely on "latest".

resources:

 - name: mjackets-api
   type: git
   public: true
   icon: github
   source:
     uri: https://github.com/RoboJackets/mjackets-api.git
     branch: master
     username: x-access-token
     password: ((github-com/token))
   webhook_token: ((webhook-token))

 - name: code-analysis
   type: sonar-runner
   source:
     host_url: https://sonarcloud.io/
     organization: robojackets
     login: ((sonarcloud-io))
     __debug: true

jobs:
- name: build-and-analyze
  plan:
  - get: mjackets-api
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: robojackets/mjackets-dev
      params:
          SONAR_TOKEN: ((sonarcloud-io))
      inputs:
       - name: mjackets-api
      outputs:
       - name: sonarqube-analysis-input
      run:
        path: sh 
        args:
        - -exc
        - |
          ./mjackets-api/ci/build_scripts/example.sh

