# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clang Format Github Action
        uses: RafikFarhad/clang-format-github-action@v1
        with:
          style: Google
          sources: ./api*, ./include*
